# Generated by Django 2.0.4 on 2018-04-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobposting_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
